import type { AnalysisResult } from "@/types/analysis";
import { MarketSpreadChart } from "./dashboard/MarketSpreadChart";
import { RiskDisclosures } from "./dashboard/RiskDisclosures";
import { LiabilityProjection } from "./dashboard/LiabilityProjection";
import { AuditorNote } from "./dashboard/AuditorNote";
import { AssetHeader } from "./dashboard/AssetHeader";
import { Button } from "@/components/ui/button";
import { FileDown, RotateCcw } from "lucide-react";

interface ResultsDashboardProps {
  result: AnalysisResult;
  onReset: () => void;
}

export function ResultsDashboard({ result, onReset }: ResultsDashboardProps) {
  const handleExport = () => {
    const report = generateReport(result);
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${result.asset_identifier.replace(/\s+/g, "_")}.info.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6">
      <AssetHeader result={result} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <MarketSpreadChart result={result} />
        <LiabilityProjection result={result} />
      </div>

      <RiskDisclosures result={result} />
      <AuditorNote result={result} />

      <div className="flex gap-3 justify-center pt-4">
        <Button variant="outline" onClick={handleExport} className="font-mono text-xs gap-2">
          <FileDown className="w-3.5 h-3.5" />
          Export .info Report
        </Button>
        <Button variant="outline" onClick={onReset} className="font-mono text-xs gap-2">
          <RotateCcw className="w-3.5 h-3.5" />
          Scan New Listing
        </Button>
      </div>
    </div>
  );
}

function generateReport(r: AnalysisResult): string {
  return `
═══════════════════════════════════════════
  CarListings.info — ASSET REPORT
═══════════════════════════════════════════

ASSET:    ${r.asset_identifier}
PRICE:    $${r.asking_price.toLocaleString()}
MILEAGE:  ${r.mileage_metric.toLocaleString()} km
VERDICT:  ${r.market_spread_verdict}

───────────────────────────────────────────
  RISK DISCLOSURES
───────────────────────────────────────────
${r.risk_disclosures.map((d) => `[${d.severity_index.toUpperCase()}] ${d.component}\n  ${d.technical_summary}`).join("\n\n")}

───────────────────────────────────────────
  PROJECTED MONTHLY LIABILITY
───────────────────────────────────────────
$${r.projected_monthly_liability.toLocaleString()}/mo

───────────────────────────────────────────
  AUDITOR NOTE
───────────────────────────────────────────
${r.auditor_note}

═══════════════════════════════════════════
  Generated by CarListings.info
  ${new Date().toISOString()}
═══════════════════════════════════════════
`.trim();
}
