import { useState, useRef } from "react";
import { FileDown, Loader2 } from "lucide-react";
import type { AnalysisResult } from "@/types/analysis";

interface ExportReportButtonProps {
  result?: AnalysisResult;
  dashboardRef?: React.RefObject<HTMLDivElement>;
}

export function ExportReportButton({ result, dashboardRef }: ExportReportButtonProps) {
  const [generating, setGenerating] = useState(false);

  const handleExport = async () => {
    if (generating) return;

    const target = dashboardRef?.current;
    if (!target) {
      // Fallback to window.print()
      window.print();
      return;
    }

    setGenerating(true);

    try {
      const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
        import("html2canvas"),
        import("jspdf"),
      ]);

      // Capture the dashboard
      const canvas = await html2canvas(target, {
        backgroundColor: "#09090b",
        scale: 2,
        useCORS: true,
        logging: false,
        windowWidth: 900,
      });

      const imgData = canvas.toDataURL("image/png");
      const imgWidth = 210; // A4 width in mm
      const pageHeight = 297; // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      const pdf = new jsPDF("p", "mm", "a4");

      // Add pages as needed for long content
      let heightLeft = imgHeight;
      let position = 0;

      // First page
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft > 0) {
        position = -(pageHeight - 0) + (imgHeight - heightLeft - pageHeight);
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, -heightLeft, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      // Add footer watermark to last page
      const lastPage = pdf.getNumberOfPages();
      pdf.setPage(lastPage);
      pdf.setFontSize(7);
      pdf.setTextColor(100, 100, 100);
      pdf.text("Generated by CarListings.info — Automotive Risk Intelligence", 105, 292, { align: "center" });

      // Generate filename
      const assetName = result?.asset_identifier?.replace(/[^a-zA-Z0-9]/g, "_") ?? "Vehicle";
      const date = new Date().toISOString().split("T")[0];
      pdf.save(`CarListings.info_Report_${assetName}_${date}.pdf`);
    } catch (e) {
      console.error("PDF generation failed:", e);
      // Fallback
      window.print();
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={generating}
      className="print:hidden inline-flex items-center gap-2 font-mono text-sm text-muted-foreground border border-border rounded-sm px-4 py-2 bg-transparent hover:bg-muted hover:text-foreground transition-colors disabled:opacity-50"
    >
      {generating ? (
        <>
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
          [ GENERATING... ]
        </>
      ) : (
        <>
          <FileDown className="w-3.5 h-3.5" />
          [ EXPORT PDF REPORT ]
        </>
      )}
    </button>
  );
}
